import Mathlib.RingTheory.AlgebraicIndependent
import Mathlib.Data.Real.Basic

/-!
# Witness (in progress) for `MachLib.chain_algebraic_dependence`

> **BUILD STATUS (2026-07-10): build-verified.** Steps 1–2 below compile against Mathlib
> (`lake exe cache get` was run to fetch the algebra hierarchy). Step 3 (the connection to
> the specific iterated-exp functions) remains.

`MachLib/DiffAlgebraic.lean` states the Route-A axiom

    chain_algebraic_dependence (N) (P : Fin (N+2) → MultiPoly N) :
      ∃ Q, Q ≠ 0 ∧ ∀ x, Q.eval x (fun i => (P i).eval x (chainValues x)) = 0

("any `N+2` polynomials in the `N+1` generators `(x, f₁,…,f_N)` of the order-`N`
iterated-exp chain satisfy a nonzero polynomial relation"). This file grounds it against
Mathlib, the same soundness-witness pattern as `rolle_witnessed` etc.

## The witness, in three steps

1. **Extraction** (`exists_nonzero_relation_of_not_algIndep`) — PROVED here. A family that
   is not `AlgebraicIndependent` has a nonzero polynomial relation. Direct from
   `algebraicIndependent_iff` (independent ⇔ `aeval` injective).

2. **Trans-degree bound** — the `N+2` chain-value functions live in the field
   `ℝ(x, f₁,…,f_N)` generated by `N+1` elements, so its transcendence degree is `≤ N+1`
   (the TRIVIAL upper bound — no independence of exponentials / Ax needed). Hence the
   `N+2` functions are not algebraically independent. Mathlib tools:
   `algebraicIndependent_bounded_of_finset_algebraicIndependent_bounded` (bounded trdeg),
   `Set.range` cardinality for the injective family, and the family⇔set independence
   conversion — assembled in `algDep_of_bounded_trdeg` (next brick).

3. **Connection** — interpret machlib's `IterExpChain N`.`chainValues` as the actual
   iterated-exp functions over Mathlib ℝ (the `MachLibRealModel` bridge for `exp`), and
   machlib's `MultiPoly.eval` as `MvPolynomial.aeval`, so step 2 yields exactly the axiom's
   `Q`. This is the bulk of the remaining work (a differential-field setup for the
   exponentials), and is what makes the witness a ~week sub-project rather than a lemma.
-/

open MvPolynomial

/-- **Extraction core.** A family that is not algebraically independent over `R` admits a
NONZERO polynomial `Q` with `aeval g Q = 0` — the polynomial relation. Immediate from the
definition of `AlgebraicIndependent` as injectivity of `aeval`. This is the reusable heart
the transcendence-degree bound (step 2) feeds into. -/
theorem exists_nonzero_relation_of_not_algIndep
    {ι R A : Type*} [CommRing R] [CommRing A] [Algebra R A] {g : ι → A}
    (h : ¬ AlgebraicIndependent R g) :
    ∃ Q : MvPolynomial ι R, Q ≠ 0 ∧ MvPolynomial.aeval g Q = 0 := by
  rw [algebraicIndependent_iff] at h
  push_neg at h
  obtain ⟨p, hp, hpne⟩ := h
  exact ⟨p, hpne, hp⟩

/-- **The trans-degree bound — step 2, PROVED.** If the transcendence degree of `A` over `ℝ`
is `≤ n+1` (stated in Mathlib's finset form `H`: every algebraically-independent finite set
has cardinality `≤ n+1`), then any injective family of `n+2` elements is algebraically
dependent: they satisfy a nonzero polynomial relation. This is the reusable core the witness
feeds the chain-value functions into — it uses only the trivial trans-degree UPPER bound.

Proof: were `g` independent, `Set.range g` would be an independent set of cardinality `n+2`
(g injective), contradicting the `≤ n+1` bound. -/
theorem algDep_of_bounded_trdeg {A : Type} [CommRing A] [Algebra ℝ A] {n : ℕ}
    (g : Fin (n + 2) → A) (hinj : Function.Injective g)
    (H : ∀ s : Finset A, (AlgebraicIndependent ℝ (fun i : s => (i : A))) → s.card ≤ n + 1) :
    ∃ Q : MvPolynomial (Fin (n + 2)) ℝ, Q ≠ 0 ∧ MvPolynomial.aeval g Q = 0 := by
  apply exists_nonzero_relation_of_not_algIndep
  intro hindep
  have hset : AlgebraicIndependent ℝ ((↑) : Set.range g → A) :=
    (algebraicIndependent_subtype_range hinj).mpr hindep
  have hbound :=
    algebraicIndependent_bounded_of_finset_algebraicIndependent_bounded H (Set.range g) hset
  have hchain : ((n + 2 : ℕ) : Cardinal) ≤ ((n + 1 : ℕ) : Cardinal) :=
    calc ((n + 2 : ℕ) : Cardinal)
        = Cardinal.mk (Fin (n + 2))    := (Cardinal.mk_fin (n + 2)).symm
      _ = Cardinal.mk (Set.range g)    := (Cardinal.mk_range_eq g hinj).symm
      _ ≤ ((n + 1 : ℕ) : Cardinal)     := hbound
  have : (n + 2 : ℕ) ≤ n + 1 := by exact_mod_cast hchain
  omega
