import Mathlib.RingTheory.AlgebraicIndependent
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.RingTheory.MvPolynomial.Basic
import Mathlib.Algebra.MvPolynomial.Funext
import Mathlib.Data.Real.Basic
import MonogateEML.TrdegExchange

/-!
# Witness (in progress) for `MachLib.chain_algebraic_dependence`

> **BUILD STATUS (2026-07-10): COMPLETE.** The axiom's content is fully witnessed against
> Mathlib, `sorryAx`-free. **(3a)** is discharged by
> `TrdegExchange.card_le_of_algebraicIndependent_span` (the Mathlib-missing finite
> transcendence-degree bound, built from scratch); **(3b)** by `chain_algDep_witness` /
> `chain_algDep_witness_pointwise` — grounded ALGEBRAICALLY, with no analytic-function domain and
> no identity theorem, contrary to the original plan. `chain_algebraic_dependence_witnessed`
> (bottom) is the faithful mirror of the axiom, both conjuncts included. Per the established
> witness pattern (cf. `mathlibModel : OrderedFieldModel`), this file does NOT import `MachLib`:
> it mirrors the axiom's *shape* over `ℝ`, so `MachLib.Real`/`MultiPoly` need not appear.

`MachLib/DiffAlgebraic.lean` states the Route-A axiom

    chain_algebraic_dependence (N) (P : Fin (N+2) → MultiPoly N) :
      ∃ Q, Q ≠ 0 ∧ ∀ x, Q.eval x (fun i => (P i).eval x (chainValues x)) = 0

("any `N+2` polynomials in the `N+1` generators `(x, f₁,…,f_N)` of the order-`N`
iterated-exp chain satisfy a nonzero polynomial relation"). This file grounds it against
Mathlib, the same soundness-witness pattern as `rolle_witnessed` etc.

## The witness, in three steps

1. **Extraction** (`exists_nonzero_relation_of_not_algIndep`) — PROVED here. A family that
   is not `AlgebraicIndependent` has a nonzero polynomial relation. Direct from
   `algebraicIndependent_iff` (independent ⇔ `aeval` injective).

2. **Trans-degree bound** — the `N+2` chain-value functions live in the field
   `ℝ(x, f₁,…,f_N)` generated by `N+1` elements, so its transcendence degree is `≤ N+1`
   (the TRIVIAL upper bound — no independence of exponentials / Ax needed). Hence the
   `N+2` functions are not algebraically independent. Mathlib tools:
   `algebraicIndependent_bounded_of_finset_algebraicIndependent_bounded` (bounded trdeg),
   `Set.range` cardinality for the injective family, and the family⇔set independence
   conversion — assembled in `algDep_of_bounded_trdeg` (next brick).

3. **Connection** — feed the actual iterated-exp polynomials to `algDep_of_bounded_trdeg`.
   Both demands are now DISCHARGED:

   * **(3a) the trans-degree bound `H`** — DONE. Built the finite transcendence-degree bound
     Mathlib lacks (`TrdegExchange.card_le_of_isAlgebraic_span` via a from-scratch
     transcendence Steinitz exchange + an `IsFractionRing` subring↔subfield bridge); its Finset
     form `TrdegExchange.card_le_of_algebraicIndependent_span` IS this `H`.
   * **(3b) grounding — DONE, and PURELY ALGEBRAIC.** No analytic-function domain, no identity
     theorem (the original real-analytic plan is unnecessary): the `N+2` chain polynomials `P i`
     lie in `ℝ[x,y₁,…,y_N] = MvPolynomial (Fin (N+1)) ℝ` (trans-deg `N+1`), so `N+2` of them are
     dependent as polynomials (`chain_algDep_witness`); substituting `yᵢ = eᵢ(x)` gives the
     pointwise `∀x` relation (`chain_algDep_witness_pointwise`). The field is just
     `Frac(MvPolynomial (Fin (N+1)) ℝ)`.

   The faithful mirror `chain_algebraic_dependence_witnessed` (bottom) assembles these into the
   axiom's exact shape: `∃ Q, (∃ pt, eval pt Q ≠ 0) ∧ ∀ x, eval (fun i => eval (Fin.cons x
   (chainValues x)) (P i)) Q = 0`. The non-vanishing-point conjunct is `MvPolynomial.funext` over
   the infinite field `ℝ`. **Nothing further is needed for the soundness witness**: matching the
   `MachLib.Real`/`MultiPoly` *types* verbatim is explicitly NOT part of this pattern — the whole
   `MachLibRealModel*` family witnesses `MachLib`'s opaque `axiom Real : Type` and its axioms by
   *mirroring their shapes* against `ℝ`, never importing `MachLib`. A literal type identification
   would instead require the `MachLib.Real ⊨ ℝ` interpretation (the `certcom` project), which is a
   different, cross-package concern.
-/

open MvPolynomial

/-- **Extraction core.** A family that is not algebraically independent over `R` admits a
NONZERO polynomial `Q` with `aeval g Q = 0` — the polynomial relation. Immediate from the
definition of `AlgebraicIndependent` as injectivity of `aeval`. This is the reusable heart
the transcendence-degree bound (step 2) feeds into. -/
theorem exists_nonzero_relation_of_not_algIndep
    {ι R A : Type*} [CommRing R] [CommRing A] [Algebra R A] {g : ι → A}
    (h : ¬ AlgebraicIndependent R g) :
    ∃ Q : MvPolynomial ι R, Q ≠ 0 ∧ MvPolynomial.aeval g Q = 0 := by
  rw [algebraicIndependent_iff] at h
  push_neg at h
  obtain ⟨p, hp, hpne⟩ := h
  exact ⟨p, hpne, hp⟩

/-- **The trans-degree bound — step 2, PROVED.** If the transcendence degree of `A` over `ℝ`
is `≤ n+1` (stated in Mathlib's finset form `H`: every algebraically-independent finite set
has cardinality `≤ n+1`), then any injective family of `n+2` elements is algebraically
dependent: they satisfy a nonzero polynomial relation. This is the reusable core the witness
feeds the chain-value functions into — it uses only the trivial trans-degree UPPER bound.

Proof: were `g` independent, `Set.range g` would be an independent set of cardinality `n+2`
(g injective), contradicting the `≤ n+1` bound. -/
theorem algDep_of_bounded_trdeg {A : Type} [CommRing A] [Algebra ℝ A] {n : ℕ}
    (g : Fin (n + 2) → A) (hinj : Function.Injective g)
    (H : ∀ s : Finset A, (AlgebraicIndependent ℝ (fun i : s => (i : A))) → s.card ≤ n + 1) :
    ∃ Q : MvPolynomial (Fin (n + 2)) ℝ, Q ≠ 0 ∧ MvPolynomial.aeval g Q = 0 := by
  apply exists_nonzero_relation_of_not_algIndep
  intro hindep
  have hset : AlgebraicIndependent ℝ ((↑) : Set.range g → A) :=
    (algebraicIndependent_subtype_range hinj).mpr hindep
  have hbound :=
    algebraicIndependent_bounded_of_finset_algebraicIndependent_bounded H (Set.range g) hset
  have hchain : ((n + 2 : ℕ) : Cardinal) ≤ ((n + 1 : ℕ) : Cardinal) :=
    calc ((n + 2 : ℕ) : Cardinal)
        = Cardinal.mk (Fin (n + 2))    := (Cardinal.mk_fin (n + 2)).symm
      _ = Cardinal.mk (Set.range g)    := (Cardinal.mk_range_eq g hinj).symm
      _ ≤ ((n + 1 : ℕ) : Cardinal)     := hbound
  have : (n + 2 : ℕ) ≤ n + 1 := by exact_mod_cast hchain
  omega

/-!
## Step (3b) — grounding the concrete chain (PURELY ALGEBRAIC, no analysis)

The abstract bound above (step 2, `algDep_of_bounded_trdeg`) is now instantiated for the
actual iterated exponentials — and, crucially, this needs **no analytic-function domain and no
identity theorem** (contrary to the original roadmap). The algebraic dependence happens at the
POLYNOMIAL level: the `N+2` chain polynomials `P i` live in `ℝ[x, y₁,…,y_N] =
MvPolynomial (Fin (N+1)) ℝ`, whose transcendence degree over `ℝ` is `N+1`, so `N+2` of them are
algebraically dependent *as polynomials*. Substituting `yᵢ = eᵢ(x)` (any functions) then hands
the pointwise `∀x` relation for free. The field is just `Frac(MvPolynomial (Fin (N+1)) ℝ)`.
-/

set_option synthInstance.maxHeartbeats 1000000
set_option maxHeartbeats 1000000

theorem gen_adjoin_top (N : ℕ) :
    IntermediateField.adjoin ℝ
      (Set.range (fun i : Fin (N+1) =>
        algebraMap (MvPolynomial (Fin (N+1)) ℝ) (FractionRing (MvPolynomial (Fin (N+1)) ℝ))
          (MvPolynomial.X i))) = ⊤ := by
  set R := MvPolynomial (Fin (N+1)) ℝ
  set E := FractionRing R
  set gen : Fin (N+1) → E := fun i => algebraMap R E (MvPolynomial.X i) with hgen
  -- image of R sits inside the adjoin
  have hR : ∀ r : R, algebraMap R E r ∈ IntermediateField.adjoin ℝ (Set.range gen) := by
    intro r
    have hmem : algebraMap R E r ∈ Algebra.adjoin ℝ (Set.range gen) := by
      have hrng : Set.range gen = (IsScalarTower.toAlgHom ℝ R E) '' (Set.range (MvPolynomial.X)) := by
        rw [← Set.range_comp]; rfl
      rw [hrng, ← AlgHom.map_adjoin, MvPolynomial.adjoin_range_X]
      exact ⟨r, trivial, rfl⟩
    exact IntermediateField.algebra_adjoin_le_adjoin ℝ _ hmem
  rw [_root_.eq_top_iff]
  rintro e -
  obtain ⟨a, b, hb, rfl⟩ := IsFractionRing.div_surjective (A := R) e
  exact div_mem (hR a) (hR b)


-- CORE (3b) WITNESS: N+2 polynomials in N+1 variables are algebraically dependent.
theorem chain_algDep_witness (N : ℕ) (P : Fin (N+2) → MvPolynomial (Fin (N+1)) ℝ) :
    ∃ Q : MvPolynomial (Fin (N+2)) ℝ, Q ≠ 0 ∧ MvPolynomial.aeval P Q = 0 := by
  classical
  have hinjA : Function.Injective
      (algebraMap (MvPolynomial (Fin (N+1)) ℝ) (FractionRing (MvPolynomial (Fin (N+1)) ℝ))) :=
    IsFractionRing.injective _ _
  have hnindep : ¬ AlgebraicIndependent ℝ P := by
    intro hP
    have hg : AlgebraicIndependent ℝ (fun i => algebraMap (MvPolynomial (Fin (N+1)) ℝ)
        (FractionRing (MvPolynomial (Fin (N+1)) ℝ)) (P i)) := by
      rw [algebraicIndependent_iff_injective_aeval] at hP ⊢
      have heq : (MvPolynomial.aeval (fun i => algebraMap (MvPolynomial (Fin (N+1)) ℝ)
              (FractionRing (MvPolynomial (Fin (N+1)) ℝ)) (P i)) :
            MvPolynomial (Fin (N+2)) ℝ →ₐ[ℝ] FractionRing (MvPolynomial (Fin (N+1)) ℝ))
          = (IsScalarTower.toAlgHom ℝ (MvPolynomial (Fin (N+1)) ℝ) _).comp (MvPolynomial.aeval P) := by
        apply MvPolynomial.algHom_ext; intro i; simp
      rw [heq, AlgHom.coe_comp]
      exact hinjA.comp hP
    set gen : Fin (N+1) → FractionRing (MvPolynomial (Fin (N+1)) ℝ) :=
      fun i => algebraMap (MvPolynomial (Fin (N+1)) ℝ)
        (FractionRing (MvPolynomial (Fin (N+1)) ℝ)) (MvPolynomial.X i) with hgendef
    have hgeninj : Function.Injective gen := hinjA.comp MvPolynomial.X_injective
    set T : Finset (FractionRing (MvPolynomial (Fin (N+1)) ℝ)) :=
      Finset.image gen Finset.univ with hTdef
    have hTcoe : (↑T : Set (FractionRing (MvPolynomial (Fin (N+1)) ℝ))) = Set.range gen := by
      rw [hTdef, Finset.coe_image, Finset.coe_univ, Set.image_univ]
    have hTcard : T.card = N + 1 := by
      rw [hTdef, Finset.card_image_of_injective _ hgeninj, Finset.card_univ, Fintype.card_fin]
    have hT : Algebra.IsAlgebraic
        (↥(IntermediateField.adjoin ℝ (↑T : Set (FractionRing (MvPolynomial (Fin (N+1)) ℝ)))))
        (FractionRing (MvPolynomial (Fin (N+1)) ℝ)) := by
      rw [hTcoe, gen_adjoin_top N]
      refine ⟨fun e => ?_⟩
      have he : e = algebraMap (↥(⊤ : IntermediateField ℝ (FractionRing (MvPolynomial (Fin (N+1)) ℝ)))) _
                     ⟨e, IntermediateField.mem_top⟩ := rfl
      rw [he]; exact isAlgebraic_algebraMap _
    have hle : (N + 2) ≤ T.card :=
      @card_le_of_isAlgebraic_span ℝ (FractionRing (MvPolynomial (Fin (N+1)) ℝ)) _ _ _ (N+2)
        (fun i => algebraMap (MvPolynomial (Fin (N+1)) ℝ)
          (FractionRing (MvPolynomial (Fin (N+1)) ℝ)) (P i)) hg T hT
    rw [hTcard] at hle; omega
  rw [algebraicIndependent_iff] at hnindep
  push_neg at hnindep
  obtain ⟨Q, hQ0, hQne⟩ := hnindep
  exact ⟨Q, hQne, hQ0⟩


-- POINTWISE form (faithful shape of the axiom): the relation holds for all x under any
-- chain-value assignment φ : ℝ → (Fin (N+1) → ℝ).
theorem chain_algDep_witness_pointwise (N : ℕ)
    (P : Fin (N+2) → MvPolynomial (Fin (N+1)) ℝ) (φ : ℝ → (Fin (N+1) → ℝ)) :
    ∃ Q : MvPolynomial (Fin (N+2)) ℝ, Q ≠ 0 ∧
      ∀ x : ℝ, MvPolynomial.eval (fun i => MvPolynomial.eval (φ x) (P i)) Q = 0 := by
  obtain ⟨Q, hQne, hQ0⟩ := chain_algDep_witness N P
  refine ⟨Q, hQne, fun x => ?_⟩
  have key : ∀ Q' : MvPolynomial (Fin (N+2)) ℝ,
      MvPolynomial.eval (fun i => MvPolynomial.eval (φ x) (P i)) Q'
        = MvPolynomial.eval (φ x) (MvPolynomial.aeval P Q') := by
    intro Q'
    induction Q' using MvPolynomial.induction_on with
    | h_C a => simp
    | h_add p q hp hq => simp [hp, hq]
    | h_X p i hp => simp [hp]
  rw [key Q, hQ0, map_zero]


/-- **Faithful mirror of `MachLib.chain_algebraic_dependence`.** Given `N+2` polynomials `P i`
in the generators `(x, y₁,…,y_N)` and ANY chain-value assignment `chainValues : ℝ → Fin N → ℝ`
(mirroring `IterExpChain.chainValues`), there is a nonzero polynomial `Q` in the `N+2`
function-values that vanishes identically:

* `∃ pt, eval pt Q ≠ 0` — mirrors the axiom's `∃ x env, Q.eval x env ≠ 0` (via `MvPolynomial.funext`
  over the infinite field `ℝ`);
* `∀ x, eval (fun i => eval (Fin.cons x (chainValues x)) (P i)) Q = 0` — mirrors
  `∀ x, Q.eval x (fun i => (P i).eval x (chainValues x)) = 0` exactly, with the `Fin.cons x (…)`
  assignment putting `x` at index `0` and the `N` chain values at `1,…,N`.

This is the `MachLib`-free soundness witness of the axiom, the same pattern as `mathlibModel :
OrderedFieldModel`: the axiom's *content* is a theorem over Mathlib's `ℝ`. (The witness `Q` does
not use the `x` variable that `MultiPoly (N+2)` additionally offers — an `x`-independent relation
is a stronger conclusion, so this exceeds what the axiom demands.) `sorryAx`-free. -/
theorem chain_algebraic_dependence_witnessed (N : ℕ)
    (P : Fin (N + 2) → MvPolynomial (Fin (N + 1)) ℝ) (chainValues : ℝ → Fin N → ℝ) :
    ∃ Q : MvPolynomial (Fin (N + 2)) ℝ,
      (∃ pt : Fin (N + 2) → ℝ, MvPolynomial.eval pt Q ≠ 0) ∧
      ∀ x : ℝ, MvPolynomial.eval
        (fun i => MvPolynomial.eval (Fin.cons x (chainValues x)) (P i)) Q = 0 := by
  obtain ⟨Q, hQne, hQpt⟩ :=
    chain_algDep_witness_pointwise N P (fun x => Fin.cons x (chainValues x))
  refine ⟨Q, ?_, hQpt⟩
  by_contra h
  push_neg at h
  exact hQne (MvPolynomial.funext (fun pt => by rw [h pt, map_zero]))
