import Mathlib.RingTheory.AlgebraicIndependent
import Mathlib.RingTheory.Algebraic.Basic
import Mathlib.Data.Real.Basic

/-!
# Transcendence-degree exchange bound (Steinitz for the algebraic matroid)

This builds the theorem Mathlib is **missing** — the transcendence analogue of the linear
Steinitz exchange (`Basis.le_span` : an independent family is bounded by any spanning
family). It is the one lemma that closes `(3a)` (the trans-degree bound `H` that
`MachLibChainAlgDep.algDep_of_bounded_trdeg` consumes), and it is a clean, self-contained
Mathlib contribution in its own right (the pinned Mathlib rev has NO transcendence-degree
file at all).

## Target (the whole point)

    theorem AlgebraicIndependent.card_le_of_isAlgebraic
        (hv : AlgebraicIndependent F v) (hw : Algebra.IsAlgebraic (adjoin F (range w)) A) :
        #ι ≤ #κ

"An algebraically independent family is bounded by any algebraically-spanning family."
Corollaries: trdeg ≤ #generators (= `(3a)`); trdeg well-defined; the `Fintype.card` form.

## Build plan (bottom-up; each piece commits only when sorry-free)

1. **Connectors** (provable now): "generated by `g` ⇒ `A` is algebraic over `adjoin F (range g)`"
   (`isAlgebraic_of_adjoin_eq_top`, below) — bridges "k generators" to the spanning hypothesis.
2. **The exchange lemma** (the crux, from the polynomial level — Mathlib has no helper):
       a algebraic over F⟨s ∪ {b}⟩,  a transcendental over F⟨s⟩  ⟹  b algebraic over F⟨s ∪ {a}⟩.
   PROOF: a's algebraicity over F⟨s,b⟩ is a nonzero bivariate relation `Q(b,a)=0` over
   `K := adjoin F s`. Read it as `Σⱼ (Σᵢ kᵢⱼ aⁱ) bʲ = 0`. If every coefficient `Σᵢ kᵢⱼ aⁱ`
   were 0 then — `a` transcendental over `K` — every `kᵢⱼ = 0`, so `Q = 0`, contradiction.
   So some coefficient in `K[a]` is nonzero: a nonzero relation for `b` over `K⟨a⟩`. ∎
   Builds on `AlgebraicIndependent.option_iff` (transcendental characterisation) and
   `MvPolynomial`/`Polynomial` rearrangement. ~the bulk of the work.
3. **The main bound** by exchange induction on the finite spanning family (van der Waerden):
   maintain "A is algebraic over `F⟨v₀,…,v_{r-1}, w_r,…⟩`"; each new `v_r`, transcendental over
   the `v`-part but algebraic over the whole, forces (via the exchange) some remaining `w` to be
   swappable — so `r < k` at each step ⇒ `#v ≤ #w`.
4. **(3a) corollary + discharge** `algDep_of_bounded_trdeg`'s `H`, closing
   `chain_algebraic_dependence` (mod step 3b, the analytic-function domain).

## Status (2026-07-10)

Scaffold + roadmap committed; imports build against the fetched Mathlib algebra hierarchy.
The exchange lemma (step 2) is the next crux — a from-scratch polynomial-level proof, since
this Mathlib has no `Transcendental.lean` and no adjoin-exchange helper. It is genuinely the
bulk of the work (Mathlib itself lacks the transcendence Steinitz exchange entirely). Building
it here doubles as a candidate Mathlib contribution.
-/
